### ISSUE TITLE
Switch to Maud for templating

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#19]
- [x] separate Diesel code out so we can use proc_macro #21 
- [x] wire up Maud #22 
- [x] reach feature parity with existing Tera templates #22

**Comment by barzamin** [comment]
Closed in #22. I forgot to close this! :grimacing:
